name: Build with cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/**
            ~/.cargo/registry/index/**
            ~/.cargo/registry/cache/**
            ~/.cargo/git/db/**
            target/**
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install rust toolchain
        run: rustup update stable && rustup default stable

      - name: Install NASM
        run: sudo apt install nasm

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Install cross
        run: cargo install --force cross

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate index and upload assets to S3
        run: cargo run  --release --package assetwrap -- --upload-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_REGION: ${{ secrets.S3_REGION }}

      - name: Display asset index
        run: cat assetindex.json

      - name: Build with cross (aarch64-unknown-linux-musl)
        run: cross build --release --target aarch64-unknown-linux-musl

      - name: Upload artifacts (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: website-arm64
          path: target/aarch64-unknown-linux-musl/release/website

      - name: Build container image
        run: docker buildx build -t ghcr.io/ashhhleyyy/website:latest -t ghcr.io/ashhhleyyy/website:${GITHUB_SHA} --platform linux/arm64 --push .
