name: Build with cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/**
            ~/.cargo/registry/index/**
            ~/.cargo/registry/cache/**
            ~/.cargo/git/db/**
            target/**
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install nix
        uses: cachix/install-nix-action@56a7bb7b56d9a92d4fd1bc05758de7eea4a370a8 # v31.6.0
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup cachix
        uses: cachix/cachix-action@v12
        with:
          name: ashhhleyyy
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install rust toolchain
        run: rustup update stable && rustup default stable

      - name: Install NASM
        run: sudo apt install nasm

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Install cross
        run: cargo install --force cross

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate index and upload assets to S3
        run: cargo run  --release --package assetwrap -- --upload-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_REGION: ${{ secrets.S3_REGION }}

      - name: Display asset index
        run: cat assetindex.json

      - name: Build website image
        run: GC_DONT_GC=1 nix build --show-trace --log-lines 10000 --fallback '.#docker.website'

      - name: Import image
        run: docker image load -f result
      
      - name: Tag image
        run: docker image tag website:latest ghcr.io/ashhhleyyy/website:${GITHUB_SHA}
      
      - name: Tag image (latest)
        run: docker image tag website:latest ghcr.io/ashhhleyyy/website:latest
      
      - name: Push image
        run: docker push ghcr.io/ashhhleyyy/website:${GITHUB_SHA}

      - name: Push image (latest)
        run: docker push ghcr.io/ashhhleyyy/website:latest
